# Generated by Django 3.1.4 on 2021-01-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='circleImage',
            field=models.ImageField(upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(upload_to='upload'),
        ),
    ]
