# Generated by Django 3.1.4 on 2021-01-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210120_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.ImageField(default=0, upload_to='', verbose_name='price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
