# Generated by Django 3.1.4 on 2021-02-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210202_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='discounts'),
        ),
    ]
